#!/bin/bash

# Copyright © 2015 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
#
# Created: 2015-01-02
# Last changed: 2016-02-01 14:10:46
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

ME=$(basename $0)
DISABLED=

function is_disabled () {
    SVC=$1
    DISABLED=/etc/init/$SVC.override
    if test -e $DISABLED; then
	grep -q -F 'manual' $DISABLED
	if test $? -eq 0; then
	    echo 1
	    return
	fi
    fi
    ischroot
    if test $? -eq 0; then
        echo 1
        return
    fi
    echo 0
}

function run_initctl () {
    ORIG=/sbin/initctl.distrib
    case $ME in
	initctl)
	    $ORIG "$@"
	    ;;
	*)
	    disabled=`is_disabled $1`
	    if test $disabled -eq 1; then
		echo "Service $1 is disabled in $DISABLED. Skipping..."
		exit 0
	    fi
	    $ORIG $ME "$@";;
    esac
}

function run_invoke_rc_d () {
    ORIG=/usr/sbin/invoke-rc.d.distrib
    disabled=`is_disabled $1`
    if test $disabled -eq 1; then
	echo "Service $1 is disabled in $DISABLE. Skipping..."
	exit 0
    fi
    $ORIG "$@"
}

function run_service () {
    ORIG=/usr/sbin/service.distrib
    disabled=`is_disabled $1`
    if test $disabled -eq 1; then
	echo "Service $1 is disabled in $DISABLE. Skipping..."
	exit 0
    fi
    $ORIG "$@"
}




case $ME in
    initctl|start|stop|reload|restart|status) run_initctl "$@";;
    invoke-rc.d) run_invoke_rc_d "$@";;
    service) run_service "$@";;
    *)
	exit 0
	;;
esac


exit $?
